config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  get '/suggest', to: "pages#suggest", as: :suggest
  get '/about', to: "pages#about", as: :about

  post 'grab', to: "profiles#grab"

  post 'suggest', to: "profiles#suggest"

  get 'profiles/json', to: "profiles#profiles_json"

  scope '/admin' do
    get '/',  to: "profiles#index", as: :admin
    resources :profiles, only: %i(create update destroy) do
      post :approve, to: :approve
    end
  end

  get 'oauth/callback', to: 'pages#oauth'
  get 'oauth/request_li_token', to: "pages#request_li_token", as: :li_token
end

app/views/pages/_aside.html.slim
sidebar :tags="#{@tags}" :opened="asideOpened" @toggleaside="toggleAside()"

app/views/pages/_header.html.slim
section#header
  .heading-title
    h4 WomanPower.md is a profile directory of inspiring Moldovan women from Tech and Creative industries.
  .button-block
    = link_to 'read more', about_path, data: { turbolinks: false }, class: 'btn heading'

app/views/pages/_profiles.html.slim
index-profiles

app/views/pages/about.html.slim
aside#foreign
  = link_to root_path do
    .header-logo
  .pages-links
    ul
      li
        = link_to 'about', about_path, data: { turbolinks: false }
      li
        = link_to 'suggest', suggest_path, data: { turbolinks: false }
main#foreign
  section#about
    .row.align-center.small-collapse
      .small-12.medium-8.large-6.columns
        .head_info-block.animated.fadeInUp
          h3 Hi! This website exists for two reasons:

          p
            span.ol 1.&nbsp;
            | To celebrate the awesome moldovan women that work in IT and creative industries. We are proud of you and you inspire us. Thank you for innovating and leading!
          p.strong and
          p
            span.ol 2.&nbsp;
            | To encourage other girls and women to join these innovative industries! Look at all these women listed on this website. They are just like you, so don't be afraid. We need your brains, passion, creativity and courage. Now it's your turn. Please take it :)
          p We hope this website will inspire more Moldovan women to innovate and lead these industries forward.
        .head_info-block.animated.fadeInUp
          h2 FAQ
          h3 Who made this website?
          p
            | This website was made by Academia Rockit, a non-profit educational project from Moldova.
            a.promo href="https://www.youtube.com/c/academiarockit" target="_blank"
              .promo-rockit
                = image_tag('rockit_academy.png')
          p
            | The initiative came from&nbsp;
            a href="https://twitter.com/ionatanmocan" target="_blank" Ion Mocan
            | &nbsp;and the coding came from&nbsp;
            a href="https://www.facebook.com/dmitriib" target="_blank" Dima Belinski
            | . This project is a rip-off of&nbsp;
            a href="http://womenwho.design" target="_blank" womenwho.design
            | &nbsp;and we dont hide it. We liked what&nbsp;
            a href="https://twitter.com/julesforrest" target="_blank" those people
            | &nbsp;did and decided to do it for Moldova.
          h3 How can I add somebody on the website?
          p
            | Click on the&nbsp;
            = link_to 'Suggest', suggest_path, target: '_blank'
            | &nbsp;button in the menu and add the link to the Twitter or Linkedin profile of the person you want to add.
          h3 How can I remove myself from the website?
          p
            | Tweet us&nbsp;
            a href="https://twitter.com/rockitacademy" target="_blank" @rockitacademy
            | &nbsp;or write us at academiarockit@gmail.com and we will remove you from the website
          h3 Why only these categories?
          p We decided to focus on the tech and creative industries only. If you think that we missed an important category write me at ionatanmocan@gmail.com
        .head_info-block.animated.fadeInUp
          h2
        = link_to 'back to directory', root_path, class: 'home animated fadeInUp'

app/views/pages/index.html.slim
= render 'aside'
main#main-container
  = render 'header'
  = render 'profiles'
scroll-top
search-box @togglesearch="toggleFormShow" :fixed-form="fixedForm" :search-query="searchQuery"
transition name="search-box"
  search-form :fixed-form="fixedForm" :search-query="searchQuery" @hide="fixedForm = false" @reset="resetSearch" @update="updateSearchQuery" v-show="fixedForm"

app/views/pages/suggest.html.slim
aside#foreign
  = link_to root_path do
    .header-logo
  .pages-links
    ul
      li
        = link_to 'about', about_path, data: { turbolinks: false }
      li
        = link_to 'suggest', suggest_path, data: { turbolinks: false }
main#foreign
  section#suggest
    suggest :tags="#{@tags}"